services:
  automate_mysql:
    image: mysql:8.0
    container_name: automate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: axioma
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 27d9IyP3Tyg19WUL8a6T
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - extractor_network

  extractor_api:
    build: .
    container_name: extractor_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=automate_mysql
      - DB_PORT=3306
      - DB_USERNAME=mysql
      - DB_PASSWORD=27d9IyP3Tyg19WUL8a6T
      - DB_NAME=axioma
    depends_on:
      - automate_mysql
    networks:
      - extractor_network
    volumes:
      - ./.env:/app/.env

volumes:
  mysql_data:

networks:
  extractor_network:
    driver: bridge