version: '3.8'

services:
  pdf-parser-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped